# curl http://localhost:4001/iot/devices \
#      -H "fiware-service: opcua opcua_car" \
#      -H "fiware-servicepath: /test/demo" \
#      -H "Content-Type: application/json" \
#      -d @add_device_NGSIv2.json

## OPC UA Client
###
GET http://localhost:4001/iot/devices
fiware-service: robot_info 
fiware-servicepath: /demo

###
POST http://localhost:4001/iot/devices
fiware-service: robot_info
fiware-servicepath: /demo
Content-Type: application/json

{
    "devices": [{
      "device_id": "MyObject",
      "service": "robot_info",
      "subservice" : "/demo",
      "entity_name": "MyObject",
      "entity_type": "MyObject",
      "endpoint": "opc.tcp://host.docker.internal:4840/freeopcua/server/",
      "attributes": [
        {
          "object_id": "2:MyVariable",
          "name": "2:MyVariable",
          "type": "Number"
        }
      ],
      "lazy": [],
      "commands": [
        {
          "object_id": "2:mymethod",
          "name": "2:mymethod",
          "type": "command"
        },
        {
          "object_id": "2:multiply",
          "name": "2:multiply",
          "type": "command"
        }
      ],
      "static_attributes": []
    }]
}

## OCB
### Query entity
GET http://localhost:1026/v2/entities/
fiware-service: robot_info 
fiware-servicepath: /demo

### Query entity by id
GET http://localhost:1026/v2/entities/MyObject/
fiware-service: robot_info 
fiware-servicepath: /demo

### Query entity by attrs
GET http://localhost:1026/v2/entities/MyObject/attrs/
fiware-service: robot_info 
fiware-servicepath: /demo

### Update Entity
PUT http://localhost:1026/v2/entities/MyObject/attrs/2:multiply?type=MyObject
fiware-service: robot_info 
fiware-servicepath: /demo
content-type: application/json

{
  "value": [{"x":"1","y":"2"}],
   "type": "command"
}

### Update Entity Order
PUT http://localhost:1026/v2/entities/Robot1/attrs/writeOrderstatus?type=Order
fiware-service: robot_info 
fiware-servicepath: /demo
content-type: application/json

{
   "value": "Success",
   "type": "command"
}


### Query entity
GET http://localhost:1026/v2/subscriptions
fiware-service: robot_info
fiware-servicepath: /demo

### Query registration
GET http://localhost:1026/v2/registrations
fiware-service: robot_info 
fiware-servicepath: /demo


### Add subscription to entity (https://quantumleap.readthedocs.io/en/latest/user/using/#orion-subscription)
# POST http://localhost:1026/v2/subscriptions
# content-type: application/json
# fiware-service: opcua opcua_car
# fiware-servicepath: /test/demo

# {
#     "description": "Test subscription",
#     "subject": {
#         "entities": [
#         {
#             "idPattern": ".*",
#             "type": "Robot"
#         }
#         ],
#         "condition": {
#             "attrs": ["Wert"]
#         }
#     },
#     "notification": {
#         "http": {
#             "url": "http://quantumleap:8668/v2/notify"
#         },
#         "attrs": [],
#         "metadata": ["dateCreated", "dateModified"]
#     }
# }