version: "3"
#secrets:
#   age_idm_auth:
#      file: age_idm_auth.txt

services:
  # iotcarsrv:
   # hostname: iotcarsrv
    # image: iotagent4fiware/opcuacarsrv:1.3.4
    # networks:
    #   - hostnet
    # ports:
     # - "5001:5001"

  iotage-order:
    hostname: iotage-order
    image: iotagent4fiware/iotagent-opcua:1.3.4
    networks:
      - hostnet
      - iotnet
    ports:
      - "4001:4001"
      - "4081:8080"
    extra_hosts:
      - "opcua_server_sps:192.168.1.10"
    depends_on:
      - iotmongo
      - orion
    volumes:
      - ./opcua/config_order:/opt/iotagent-opcua/conf
    environment:
      - IOTA_REGISTRY_TYPE=memory
      - IOTA_LOG_LEVEL=DEBUG # The log level of the IoT Agent
      - IOTA_MONGO_HOST=iotmongo # The host name of MongoDB
      - IOTA_MONGO_DB=iotagent_opcua # The name of the database used in mongoDB
      - IOTA_CB_NGSI_VERSION=v2

    command: /usr/bin/tail -f /var/log/lastlog

  iotage-processdata:
    hostname: iotage-processdata
    image: iotagent4fiware/iotagent-opcua:1.3.4
    networks:
      - hostnet
      - iotnet
    ports:
      - "4002:4001"
      - "4082:8080"
    extra_hosts:
      - "opcua_server_sps:192.168.1.10"
    depends_on:
      - iotmongo
      - orion
    volumes:
      - ./opcua/config_processdata:/opt/iotagent-opcua/conf
    environment:
      - IOTA_REGISTRY_TYPE=memory
      - IOTA_LOG_LEVEL=DEBUG # The log level of the IoT Agent
      - IOTA_MONGO_HOST=iotmongo # The host name of MongoDB
      - IOTA_MONGO_DB=iotagent_opcua # The name of the database used in mongoDB
      - IOTA_CB_NGSI_VERSION=v2

    command: /usr/bin/tail -f /var/log/lastlog

  iotage-product:
    hostname: iotage-product
    image: iotagent4fiware/iotagent-opcua:1.3.4
    networks:
      - hostnet
      - iotnet
    ports:
      - "4003:4001"
      - "4083:8080"
    extra_hosts:
      - "opcua_server_sps:192.168.1.10"
    depends_on:
      - iotmongo
      - orion
    volumes:
      - ./opcua/config_product:/opt/iotagent-opcua/conf
    environment:
      - IOTA_REGISTRY_TYPE=memory
      - IOTA_LOG_LEVEL=DEBUG # The log level of the IoT Agent
      - IOTA_MONGO_HOST=iotmongo # The host name of MongoDB
      - IOTA_MONGO_DB=iotagent_opcua # The name of the database used in mongoDB
      - IOTA_CB_NGSI_VERSION=v2

    command: /usr/bin/tail -f /var/log/lastlog

  iotage-versionreq:
    hostname: iotage-versionreq
    image: iotagent4fiware/iotagent-opcua:1.3.4
    networks:
      - hostnet
      - iotnet
    ports:
      - "4004:4001"
      - "4084:8080"
    extra_hosts:
      - "opcua_server_sps:192.168.1.10"
    depends_on:
      - iotmongo
      - orion
    volumes:
      - ./opcua/config_versionreq:/opt/iotagent-opcua/conf
    environment:
      - IOTA_REGISTRY_TYPE=memory
      - IOTA_LOG_LEVEL=DEBUG # The log level of the IoT Agent
      - IOTA_MONGO_HOST=iotmongo # The host name of MongoDB
      - IOTA_MONGO_DB=iotagent_opcua # The name of the database used in mongoDB
      - IOTA_CB_NGSI_VERSION=v2

    command: /usr/bin/tail -f /var/log/lastlog

  iotage-robtoservreq:
    hostname: iotage-robtoservreq
    image: iotagent4fiware/iotagent-opcua:1.3.4
    networks:
      - hostnet
      - iotnet
    ports:
      - "4005:4001"
      - "4085:8080"
    extra_hosts:
      - "opcua_server_sps:192.168.1.10"
    depends_on:
      - iotmongo
      - orion
    volumes:
      - ./opcua/config_robtoservreq:/opt/iotagent-opcua/conf
    environment:
      - IOTA_REGISTRY_TYPE=memory
      - IOTA_LOG_LEVEL=DEBUG # The log level of the IoT Agent
      - IOTA_MONGO_HOST=iotmongo # The host name of MongoDB
      - IOTA_MONGO_DB=iotagent_opcua # The name of the database used in mongoDB
      - IOTA_CB_NGSI_VERSION=v2

    command: /usr/bin/tail -f /var/log/lastlog

  iotage-servtorobreq:
    hostname: iotage-servtorobreq
    image: iotagent4fiware/iotagent-opcua:1.3.4
    networks:
      - hostnet
      - iotnet
    ports:
      - "4006:4001"
      - "4086:8080"
    extra_hosts:
      - "opcua_server_sps:192.168.1.10"
    depends_on:
      - iotmongo
      - orion
    volumes:
      - ./opcua/config_servtorobreq:/opt/iotagent-opcua/conf
    environment:
      - IOTA_REGISTRY_TYPE=memory
      - IOTA_LOG_LEVEL=DEBUG # The log level of the IoT Agent
      - IOTA_MONGO_HOST=iotmongo # The host name of MongoDB
      - IOTA_MONGO_DB=iotagent_opcua # The name of the database used in mongoDB
      - IOTA_CB_NGSI_VERSION=v2

    command: /usr/bin/tail -f /var/log/lastlog

  iotage-orderreq:
    hostname: iotage-orderreq
    image: iotagent4fiware/iotagent-opcua:1.3.4
    networks:
      - hostnet
      - iotnet
    ports:
      - "4007:4001"
      - "4087:8080"
    extra_hosts:
      - "opcua_server_sps:192.168.1.10"
    depends_on:
      - iotmongo
      - orion
    volumes:
      - ./opcua/config_orderreq:/opt/iotagent-opcua/conf
    environment:
      - IOTA_REGISTRY_TYPE=memory
      - IOTA_LOG_LEVEL=DEBUG # The log level of the IoT Agent
      - IOTA_MONGO_HOST=iotmongo # The host name of MongoDB
      - IOTA_MONGO_DB=iotagent_opcua # The name of the database used in mongoDB
      - IOTA_CB_NGSI_VERSION=v2

    command: /usr/bin/tail -f /var/log/lastlog

  iotmongo:
    hostname: iotmongo
    image: mongo:3.4
    networks:
      - iotnet
    volumes:
      - iotmongo_data:/data/db
      - iotmongo_conf:/data/configdb

  ################ OCB ################

  orion:
    hostname: orion
    image: fiware/orion:latest
    networks:
      - hostnet
      - ocbnet
    ports:
      - "1026:1026"
    depends_on:
      - orion_mongo
    entrypoint: /usr/bin/contextBroker -fg -multiservice -ngsiv1Autocast -statCounters -dbhost mongo -logForHumans -logLevel DEBUG -t 255

  orion_mongo:
    hostname: orion_mongo
    image: mongo:3.4
    networks:
      ocbnet:
        aliases:
          - mongo
    volumes:
      - orion_mongo_data:/data/db
      - orion_mongo_conf:/data/configdb
    command: --nojournal


    ############## CrateDB #########
    # Quantum Leap is persisting Short Term History to Crate-DB
  quantumleap:
    image: smartsdk/quantumleap:0.8
    networks:
      - hostnet
      - iotnet
    hostname: quantumleap
    container_name: fiware-quantumleap
    restart: always
    ports:
      - "8668:8668"
    depends_on:
      - crate-db
    environment:
      - CRATE_HOST=crate-db
    healthcheck:
      test: curl --fail -s http://quantumleap:8668/version || exit 1
  crate-db:
    image: crate:4.7.1
    networks:
      - hostnet
      - iotnet
    hostname: crate-db
    container_name: db-crate
    restart: always
    ports:
      # Admin UI
      - "4200:4200"
      # Transport protocol
      - "4300:4300"
    command: crate -Cauth.host_based.enabled=false  -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"
    volumes:
      - crate-db:/data



  rowaconsoleclient:
    image: rowaconsoleclient
    build:
      context: .
      dockerfile: ./Dockerfile

  pythonapplication1:
    image: pythonapplication1
    build:
      context: .
      dockerfile: ./subscription_manager/Dockerfile
    ports:
      - 5011:5011

volumes:
  iotmongo_data:
  iotmongo_conf:
  orion_mongo_data:
  orion_mongo_conf:
  crate-db:

networks:
  hostnet:
  iotnet:
  ocbnet:
