version: '3.9'
services:

  orion:
    hostname: orion
    image: fiware/orion:latest
    networks:
      - hostnet
      - ocbnet
    ports:
      - "1026:1026"
    depends_on:
      - orion_mongo
    entrypoint: /usr/bin/contextBroker -fg -multiservice -ngsiv1Autocast -statCounters -dbhost mongo -logForHumans -logLevel DEBUG -t 255

  orion_mongo:
    hostname: orion_mongo
    image: mongo:3.4
    networks:
      ocbnet:
        aliases:
          - mongo
    volumes:
      - orion_mongo_data:/data/db
      - orion_mongo_conf:/data/configdb
    command: --nojournal

 # Quantum Leap is persisting Short Term History to Crate-DB
  quantumleap:
    image: smartsdk/quantumleap:0.8
    networks:
      - hostnet
    hostname: quantumleap
    container_name: fiware-quantumleap
    restart: always
    ports:
      - "8668:8668"
    depends_on:
      - crate-db
    environment:
      - CRATE_HOST=crate-db
    healthcheck:
      test: curl --fail -s http://quantumleap:8668/version || exit 1
  crate-db:
    image: crate:4.7.1
    networks:
      - hostnet
    hostname: crate-db
    container_name: db-crate
    restart: always
    ports:
      # Admin UI
      - "4200:4200"
      # Transport protocol
      - "4300:4300"
    command: crate -Cauth.host_based.enabled=false  -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"
    volumes:
      - crate-db:/data
  superset:
    hostname: superset
    image: my-superset:02 #Image from dockerfile is used
    container_name: superset
    ports:
      - "8080:8088"
    depends_on:
      - crate-db
    networks:
      - hostnet
volumes:
  crate-db:
  orion_mongo_data: 
  orion_mongo_conf:

networks:
  hostnet:
  iotnet:
  ocbnet:
  
