version: "3"
#secrets:
#   age_idm_auth:
#      file: age_idm_auth.txt

services:
  # iotcarsrv:
   # hostname: iotcarsrv
    # image: iotagent4fiware/opcuacarsrv:1.3.4
    # networks:
    #   - hostnet
    # ports:
     # - "5001:5001"

  iotage:
    hostname: iotage
    image: iotagent4fiware/iotagent-opcua:1.3.4
    networks:
      - hostnet
      - iotnet
    ports:
      - "4001:4001"
      - "4081:8080"
      #- "4840:8080"
    extra_hosts:
      - "opcua_server_sps:192.168.1.10"
      #- "testitest:192.168.1.10"
    depends_on:
    #  - iotcarsrv
      - iotmongo
      - orion
    volumes:
      - ../config:/opt/iotagent-opcua/conf

    command: /usr/bin/tail -f /var/log/lastlog

  iotmongo:
    hostname: iotmongo
    image: mongo:3.4
    networks:
      - iotnet
    volumes:
      - iotmongo_data:/data/db
      - iotmongo_conf:/data/configdb

  ################ OCB ################

  orion:
    hostname: orion
    image: fiware/orion:latest
    networks:
      - hostnet
      - ocbnet
    #  - iotnet
    ports:
      - "1026:1026"
    depends_on:
      - orion_mongo
    #command: -dbhost mongo
    entrypoint: /usr/bin/contextBroker -fg -multiservice -ngsiv1Autocast -statCounters -dbhost mongo -logForHumans -logLevel DEBUG -t 255

  orion_mongo:
    hostname: orion_mongo
    image: mongo:3.4
    networks:
      ocbnet:
        aliases:
          - mongo
    volumes:
      - orion_mongo_data:/data/db
      - orion_mongo_conf:/data/configdb
    command: --nojournal


    ############## CrateDB #########
    # Quantum Leap is persisting Short Term History to Crate-DB
  quantumleap:
    image: smartsdk/quantumleap:0.8
    networks:
      - hostnet
      - iotnet
    hostname: quantumleap
    container_name: fiware-quantumleap
    restart: always
    ports:
      - "8668:8668"
    depends_on:
      - crate-db
    environment:
      - CRATE_HOST=crate-db
    healthcheck:
      test: curl --fail -s http://quantumleap:8668/version || exit 1
  crate-db:
    image: crate:4.7.1
    networks:
      - hostnet
      - iotnet
    hostname: crate-db
    container_name: db-crate
    restart: always
    ports:
      # Admin UI
      - "4200:4200"
      # Transport protocol
      - "4300:4300"
    command: crate -Cauth.host_based.enabled=false  -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"
    volumes:
      - crate-db:/data

volumes:
  iotmongo_data:
  iotmongo_conf:
  orion_mongo_data:
  orion_mongo_conf:
  crate-db:

networks:
  hostnet:
  iotnet:
  ocbnet:
