version: "3.9"

services:
  mongo:
    image: mongo:4.4
    command: --nojournal
    volumes:
      - mongodb-volume:/data/db
  orion:
    image: fiware/orion
    links:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo
  pgh-backend:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - ./testApp:/app
    tty: true


volumes:
  mongodb-volume: