version: "3.9"

services:
  mongo:
    image: mongo:4.4
    command: --nojournal
    volumes:
      - mongodb-volume:/data/db
  orion:
    image: fiware/orion
    links:
      - mongo
      - pgh-backend
    ports:
      - "1026:1026"
    command: -dbhost mongo -logLevel DEBUG
  pghbackend:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    ports:
      - "5001:5001"
    volumes:
      - ./Fiware:/app
    command: [bash, -c, "cd /app && dotnet dev-certs https --trust && dotnet watch run -v --urls=http://0.0.0.0:5001/"]


volumes:
  mongodb-volume: