curl http://localhost:4001/iot/devices \
     -H "fiware-service: opcua_car" \
     -H "fiware-servicepath: /demo" \
     -H "Content-Type: application/json" \
     -d @add_device_NGSIv2.json

###
POST http://localhost:4001/iot/devices
fiware-service: opcua_car
fiware-servicepath: /demo
Content-Type: application/json
-d @add_device_NGSIv2.json

###
POST http://localhost:4001/iot/devices
fiware-service: opcua_car
fiware-servicepath: /demo
Content-Type: application/json

{
    "devices": [
        {
            "device_id": "age04_Car",
            "entity_name": "age04_Car",
            "entity_type": "Device",
            "attributes": [
                {
                    "object_id": "ns=3;s=EngineBrake",
                    "name": "EngineBrake",
                    "type": "Number"
                },
                {
                    "object_id": "ns=3;s=Acceleration",
                    "name": "Acceleration",
                    "type": "Number"
                },
                {
                    "object_id": "ns=3;s=EngineStopped",
                    "name": "EngineStopped",
                    "type": "Boolean"
                },
                {
                    "object_id": "ns=3;s=Temperature",
                    "name": "Temperature",
                    "type": "Number"
                },
                {
                    "object_id": "ns=3;s=Oxigen",
                    "name": "Oxigen",
                    "type": "Number"
                }
            ],
            "lazy": [{
                    "object_id": "ns=3;s=Speed",
                    "name": "Speed",
                    "type": "Number"
                }
            ],
            "commands" : [{
                "object_id": "ns=3;s=Stop",
                "name" : "Stop",
                "type" : "command"
            }, {
                "object_id": "ns=3;s=Accelerate",
                "name" : "Accelerate",
                "type" : "command"
            }]
      }
    ]
}



###
GET http://localhost:4001/iot/devices/age04_Car
fiware-service: opcua_car
fiware-servicepath: /demo



### Query entity
GET http://localhost:1026/v2/entities/Robot1
fiware-service: opcua_car
fiware-servicepath: /demo


### Update Entity
PATCH http://localhost:1026/v2/entities/Robot1/attrs
fiware-service: opcua_car
fiware-servicepath: /demo
content-type: application/json

{
  "Wert": {
    "value": 1,
    "type": "command"
  }
}


### Query entity
GET http://localhost:1026/v2/subscriptions
fiware-service: opcua_car
fiware-servicepath: /demo


### Query entity
GET http://localhost:1026/v2/registrations
fiware-service: opcua_car
fiware-servicepath: /demo