## Test connections
### test connection ocb
GET http://localhost:1026/version

### test connection quantumleap
GET http://localhost:8668/version

## Add test entity
### Entity creation
POST http://localhost:1026/v2/entities/
content-type: application/json

{
  "id": "Room1",
  "type": "Room",
  "temperature": {
    "value": 27,
    "type": "Float"
  },
  "pressure": {
    "value": 720,
    "type": "Integer"
  }
}

### Add subscription to entity (https://quantumleap.readthedocs.io/en/latest/user/using/#orion-subscription)
POST http://localhost:1026/v2/subscriptions
content-type: application/json

{
    "description": "Test subscription",
    "subject": {
        "entities": [
        {
            "idPattern": ".*",
            "type": "Room"
        }
        ],
        "condition": {
            "attrs": [
            "temperature"
            ]
        }
    },
    "notification": {
        "http": {
            "url": "http://quantumleap:8668/v2/notify"
        },
        "attrs": [],
        "metadata": ["dateCreated", "dateModified"]
    }
}

### check subscriptions
GET http://localhost:1026/v2/subscriptions

### Update Entity
PATCH http://localhost:1026/v2/entities/Room1/attrs
content-type: application/json

{
  "temperature": {
    "value": 50,
    "type": "Float"
  },
  "pressure": {
    "value": 720,
    "type": "Integer"
  }
}

## Check crate db in Browser
 http://localhost:4200/#!/console?query=SELECT%20entity_id,%20entity_type,%20time_index,%20fiware_servicepath,%20__original_ngsi_entity__,%20pressure,%20temperature%0AFROM%20%22doc%22.%22etroom%22%0ALIMIT%20100;

